### ISSUE TITLE
unicorn-worker-killer + devise + warden throwing error

### ISSUE THREAD

**Issue by cameronbourgeois** [kzk/unicorn-worker-killer#66]
When visiting a page that previously would have rendered a 404 page in my rails app, I am now getting a 500 error (after adding unicorn-worker-killer).

I get the following error in my unicorn error log:
```
Error during failsafe response: uncaught throw :warden
  /home/deploy/.bundler/my_app/ruby/2.3.0/gems/warden-1.2.6/lib/warden/proxy.rb:128:in `throw'
  /home/deploy/.bundler/my_app/ruby/2.3.0/gems/warden-1.2.6/lib/warden/proxy.rb:128:in `authenticate!'
  /home/deploy/.bundler/my_app/ruby/2.3.0/gems/devise-3.5.6/lib/devise/controllers/helpers.rb:116:in `authenticate_user!'
  /home/deploy/.bundler/my_app/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:432:in `block in make_lambda'
  /home/deploy/.bundler/my_app/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:145:in `block in halting_and_conditional'
  /home/deploy/.bundler/my_app/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:504:in `block in call'
  /home/deploy/.bundler/my_app/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:504:in `each'
  /home/deploy/.bundler/my_app/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:504:in `call'
  /home/deploy/.bundler/my_app/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:92:in `__run_callbacks__'
  /home/deploy/.bundler/my_app/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:778:in `_run_process_action_callbacks'
  /home/deploy/.bundler/my_app/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:81:in `run_callbacks'
  /home/deploy/.bundler/my_app/ruby/2.3.0/gems/actionpack-4.2.7.1/lib/abstract_controller/callbacks.rb:19:in `process_action'
  /home/deploy/.bundler/my_app/ruby/2.3.0/gems/actionpack-4.2.7.1/lib/action_controller/metal/rescue.rb:29:in `process_action'
  /home/deploy/.bundler/my_app/ruby/2.3.0/gems/actionpack-4.2.7.1/lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
  /home/deploy/.bundler/my_app/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/notifications.rb:164:in `block in instrument'
  /home/deploy/.bundler/my_app/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  /home/deploy/.bundler/my_app/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/notifications.rb:164:in `instrument'
  /home/deploy/.bundler/my_app/ruby/2.3.0/gems/actionpack-4.2.7.1/lib/action_controller/metal/instrumentation.rb:30:in `process_action'
  /home/deploy/.bundler/my_app/ruby/2.3.0/gems/actionpack-4.2.7.1/lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
  /home/deploy/.bundler/my_app/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/railties/controller_runtime.rb:18:in `process_action'
  /home/deploy/.bundler/my_app/ruby/2.3.0/gems/actionpack-4.2.7.1/lib/abstract_controller/base.rb:137:in `process'
  /home/deploy/.bundler/my_app/ruby/2.3.0/gems/actionview-4.2.7.1/lib/action_view/rendering.rb:30:in `process'
  /home/deploy/.bundler/my_app/ruby/2.3.0/gems/actionpack-4.2.7.1/lib/action_controller/metal.rb:196:in `dispatch'
  /home/deploy/.bundler/my_app/ruby/2.3.0/gems/actionpack-4.2.7.1/lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
  /home/deploy/.bundler/my_app/ruby/2.3.0/gems/actionpack-4.2.7.1/lib/action_controller/metal.rb:237:in `block in action'
  /home/deploy/.bundler/my_app/ruby/2.3.0/gems/actionpack-4.2.7.1/lib/action_dispatch/routing/route_set.rb:74:in `dispatch'
  /home/deploy/.bundler/my_app/ruby/2.3.0/gems/actionpack-4.2.7.1/lib/action_dispatch/routing/route_set.rb:43:in `serve'
  /home/deploy/.bundler/my_app/ruby/2.3.0/gems/actionpack-4.2.7.1/lib/action_dispatch/journey/router.rb:43:in `block in serve'
  /home/deploy/.bundler/my_app/ruby/2.3.0/gems/actionpack-4.2.7.1/lib/action_dispatch/journey/router.rb:30:in `each'
  /home/deploy/.bundler/my_app/ruby/2.3.0/gems/actionpack-4.2.7.1/lib/action_dispatch/journey/router.rb:30:in `serve'
  /home/deploy/.bundler/my_app/ruby/2.3.0/gems/actionpack-4.2.7.1/lib/action_dispatch/routing/route_set.rb:817:in `call'
  /home/deploy/.bundler/my_app/ruby/2.3.0/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/show_exceptions.rb:47:in `render_exception'
  /home/deploy/.bundler/my_app/ruby/2.3.0/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/show_exceptions.rb:35:in `rescue in call'
  /home/deploy/.bundler/my_app/ruby/2.3.0/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  /home/deploy/.bundler/my_app/ruby/2.3.0/gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  /home/deploy/.bundler/my_app/ruby/2.3.0/gems/railties-4.2.7.1/lib/rails/rack/logger.rb:38:in `call_app'
  /home/deploy/.bundler/my_app/ruby/2.3.0/gems/railties-4.2.7.1/lib/rails/rack/logger.rb:20:in `block in call'
  /home/deploy/.bundler/my_app/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/tagged_logging.rb:68:in `block in tagged'
  /home/deploy/.bundler/my_app/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/tagged_logging.rb:26:in `tagged'
  /home/deploy/.bundler/my_app/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/tagged_logging.rb:68:in `tagged'
  /home/deploy/.bundler/my_app/ruby/2.3.0/gems/railties-4.2.7.1/lib/rails/rack/logger.rb:20:in `call'
  /home/deploy/.bundler/my_app/ruby/2.3.0/gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  /home/deploy/.bundler/my_app/ruby/2.3.0/gems/request_store-1.3.0/lib/request_store/middleware.rb:9:in `call'
  /home/deploy/.bundler/my_app/ruby/2.3.0/gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  /home/deploy/.bundler/my_app/ruby/2.3.0/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/request_id.rb:21:in `call'
  /home/deploy/.bundler/my_app/ruby/2.3.0/gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  /home/deploy/.bundler/my_app/ruby/2.3.0/gems/rack-1.6.4/lib/rack/methodoverride.rb:22:in `call'
  /home/deploy/.bundler/my_app/ruby/2.3.0/gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  /home/deploy/.bundler/my_app/ruby/2.3.0/gems/rack-1.6.4/lib/rack/runtime.rb:18:in `call'
  /home/deploy/.bundler/my_app/ruby/2.3.0/gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  /home/deploy/.bundler/my_app/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
  /home/deploy/.bundler/my_app/ruby/2.3.0/gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  /home/deploy/.bundler/my_app/ruby/2.3.0/gems/rack-1.6.4/lib/rack/sendfile.rb:113:in `call'
  /home/deploy/.bundler/my_app/ruby/2.3.0/gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  /home/deploy/.bundler/my_app/ruby/2.3.0/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/ssl.rb:24:in `call'
  /home/deploy/.bundler/my_app/ruby/2.3.0/gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  /home/deploy/.bundler/my_app/ruby/2.3.0/gems/railties-4.2.7.1/lib/rails/engine.rb:518:in `call'
  /home/deploy/.bundler/my_app/ruby/2.3.0/gems/railties-4.2.7.1/lib/rails/application.rb:165:in `call'
  /home/deploy/.bundler/my_app/ruby/2.3.0/gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  /home/deploy/.bundler/my_app/ruby/2.3.0/gems/unicorn-5.0.1/lib/unicorn/http_server.rb:562:in `process_client'
  /home/deploy/.bundler/my_app/ruby/2.3.0/gems/unicorn-5.0.1/lib/unicorn/http_server.rb:658:in `worker_loop'
  /home/deploy/.bundler/my_app/ruby/2.3.0/gems/unicorn-5.0.1/lib/unicorn/http_server.rb:508:in `spawn_missing_workers'
  /home/deploy/.bundler/my_app/ruby/2.3.0/gems/unicorn-5.0.1/lib/unicorn/http_server.rb:132:in `start'
  /home/deploy/.bundler/my_app/ruby/2.3.0/gems/unicorn-5.0.1/bin/unicorn_rails:209:in `<top (required)>'
  /home/deploy/.bundler/my_app/ruby/2.3.0/bin/unicorn_rails:23:in `load'
  /home/deploy/.bundler/my_app/ruby/2.3.0/bin/unicorn_rails:23:in `<main>'
```

Anyone else getting this error? Any ideas?

**Comment by stevendaniels** [comment]
@cameronbourgeois - This is pretty old issue. Is this still a problem or can you close this issue?
