### ISSUE TITLE
Question: with puma

### ISSUE THREAD

**Issue by oshanz** [kzk/unicorn-worker-killer#70]
we use unicorn in the production environment only. wan't to use puma in development environment.
this is the error i get
```
/Users/oshanw/.asdf/installs/ruby/2.3.4/lib/ruby/gems/2.3.0/gems/unicorn-worker-killer-0.4.4/lib/unicorn/worker_killer/configuration.rb:1:in `<top (required)>': uninitialized constant Unicorn (NameError)
	from /Users/oshanw/.asdf/installs/ruby/2.3.4/lib/ruby/gems/2.3.0/gems/unicorn-worker-killer-0.4.4/lib/unicorn/worker_killer.rb:1:in `<top (required)>'
	from /Users/oshanw/Documents/server/config.ru:5:in `block in <main>'
	from /Users/oshanw/.asdf/installs/ruby/2.3.4/lib/ruby/gems/2.3.0/gems/rack-1.5.5/lib/rack/builder.rb:55:in `instance_eval'
	from /Users/oshanw/.asdf/installs/ruby/2.3.4/lib/ruby/gems/2.3.0/gems/rack-1.5.5/lib/rack/builder.rb:55:in `initialize'
	from /Users/oshanw/Documents/server/config.ru:in `new'
	from /Users/oshanw/Documents/server/config.ru:in `<main>'
```
so how can we configured config.ru into exclude development environment

**Comment by Arakaki** [comment]
@oshanz 

How is this?
```
unless Rails.env == 'development'
  # Unicorn self-process killer
  require 'unicorn/worker_killer'

  # Max requests per worker
  use Unicorn::WorkerKiller::MaxRequests, 3072, 4096

  # Max memory size (RSS) per worker
  use Unicorn::WorkerKiller::Oom, (192*(1024**2)), (256*(1024**2))
end

require ::File.expand_path('../config/environment', __FILE__)
run Rails.application
```

**Comment by oshanz** [comment]
@Arakaki Thank you. we tried that also, it worked perfectly with Rails 4.2 but in Rails 5 there were some errors. like Rails undefined(i can't recall exact error now). in the end, we switched to the Puma. so I'll close this now.
